name: Transfer to Mega
on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'ضع رابط الملف هنا'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests mega.py
      - name: Run Script
        run: python upload_to_mega.py "${{ github.event.inputs.file_url }}"
        env:
          MEGA_EMAIL: ${{ secrets.MEGA_EMAIL }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
